include:
  ## https://git.custis.ru/devops/include/default
  - project: devops/include/default
    file: 
      - dotnet.yml
      - npm.yml
      - git.yml
      - version.yml

stages:
  - pack
  - publish-nuget

pack:
  extends: .pack-dotnet-nuget

publish-nuget:
  extends: .publish-dotnet-nuget

## Сборка и упаковка для nuget
.pack-dotnet-nuget:
  stage: pack
  image: ${DOTNET_SDK_IMAGE}
  tags: [office-custis-ru]
  allow_failure: false
  variables:
    DOTNET_STATE: "pack"
    DOTNET_OUT: "${CI_PROJECT_DIR}/dotnet_out"
  script:
    - !reference [.get-version]
    - !reference [.get-version-tag]
    - !reference [.npm-add-config-nexus]
    - !reference [.dotnet-add-nuget-config]
    - !reference [.dotnet-project]
    - !reference [.dotnet-project-version]
    - !reference [.add-git-tag]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^((fix|rel|release)(\/|-|_))(([0-9]+)(|\.[0-9]+)(|\.[0-9]+)(|\.[0-9]+))$/
      when: on_success
      variables:
        COMMIT_TAGGING: "false"
    - if: $CI_COMMIT_TAG
      when: on_success
    - if: $CI_COMMIT_REF_NAME =~ /^(master|main)$/ || $CI_COMMIT_REF_NAME == $GIT_MAIN_BRANCH
      when: on_success
      variables:
        GET_VERSION_MAIN: "false"
    - when: never
  artifacts:
    paths:
      - ${DOTNET_OUT}/
    expire_in: 1 day


## Публикация в nuget.org
.publish-dotnet-nuget:
  stage: publish
  image: ${DOTNET_SDK_IMAGE}
  tags: [office-custis-ru]
  retry: 1
  variables:
    NUGET_TARGET: "nuget"
    NUGET_SKIP_DUPLICATE: "true"
  script:
    - !reference [.dotnet-project-nuget]
  needs:
    - job: pack
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $NUGET_API_KEY == null || $NUGET_PUBLISH == "false" || $CI_COMMIT_REF_NAME =~ /^feature\/.*$/
      when: never
    - if: $NUGET_PUBLISH_MAIN == "false" && $CI_COMMIT_REF_NAME =~ /^(master|main)$/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master|main)$/ && $NUGET_PUBLISH_MAIN == "false"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^(master|main)|((fix|rel|release)(\/|-|_))(([0-9]+)(|\.[0-9]+)(|\.[0-9]+)(|\.[0-9]+))$/ && $NUGET_AUTO == "true"
      when: on_success
    - if: $CI_COMMIT_REF_NAME =~ /^(master|main)|((fix|rel|release)(\/|-|_))(([0-9]+)(|\.[0-9]+)(|\.[0-9]+)(|\.[0-9]+))$/
      when: manual
    - if: $CI_COMMIT_TAG && $NUGET_AUTO_TAG == "true"
      when: on_success
    - if: $CI_COMMIT_TAG
      when: manual
    - when: never
