language: csharp
sudo: required
mono: none
dotnet: 3.1
dist: trusty
services:
  - docker
env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
before_script:
  - wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz'
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - dotnet user-secrets set DB 
  - dotnet user-secrets set Schema 
  - dotnet user-secrets set Pwd 
script:
  - dotnet test ./CUSTIS.OracleIdempotentSqlGenerator.Tests -c Release -f netcoreapp3.1